package com.example.tronicles.fitnesshelper;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioButton;

/**
 * Created by Tronicles on 4/16/2018.
 */

public class MacroCalc extends AppCompatActivity {

    EditText editAge, editWeight, feet, inches;
    RadioButton male, female, sedentary, light, moderate, extreme, losemore, loseless, maintain, gainmore, gainless;
    Button calc;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.macro_calc);

        editAge = findViewById(R.id.editAge);
        editWeight = findViewById(R.id.editWeight);
        feet = findViewById(R.id.feet);
        inches = findViewById(R.id.inches);
        male = findViewById(R.id.male);
        female = findViewById(R.id.female);
        sedentary = findViewById(R.id.sedentary);
        light = findViewById(R.id.light);
        moderate = findViewById(R.id.moderate);
        extreme = findViewById(R.id.extreme);
        loseless = findViewById(R.id.loseless);
        losemore = findViewById(R.id.losemore);
        gainless = findViewById(R.id.gainless);
        gainmore = findViewById(R.id.gainmore);
        maintain = findViewById(R.id.maintain);
        calc = findViewById(R.id.calc);

        calc.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                double f, i, lb, mREE, fREE, mTDEE, fTDEE, newTDEE, netCarb, netProt, netFat, totCarb, totProt, totFat;
                f = Double.parseDouble(feet.getText().toString())*30.48;
                i = Double.parseDouble(inches.getText().toString())*2.54;
                lb = Double.parseDouble(editWeight.getText().toString())*.453592;
                Intent intent = new Intent(getApplicationContext(), MacroResults.class);
                Bundle bundle = new Bundle();

                if (male.isChecked() && sedentary.isChecked() && losemore.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.2);
                    newTDEE = mTDEE - (mTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && sedentary.isChecked() && loseless.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.2);
                    newTDEE = mTDEE - (mTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && sedentary.isChecked() && maintain.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.2);
                    newTDEE = mTDEE;
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && sedentary.isChecked() && gainmore.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.2);
                    newTDEE = mTDEE + (mTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && sedentary.isChecked() && gainless.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.2);
                    newTDEE = mTDEE + (mTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && light.isChecked() && losemore.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.375);
                    newTDEE = mTDEE - (mTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && light.isChecked() && loseless.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.375);
                    newTDEE = mTDEE - (mTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && light.isChecked() && maintain.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.375);
                    newTDEE = mTDEE;
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (mTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && light.isChecked() && gainmore.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.375);
                    newTDEE = mTDEE + (mTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && light.isChecked() && gainless.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.375);
                    newTDEE = mTDEE + (mTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && moderate.isChecked() && losemore.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.55);
                    newTDEE = mTDEE - (mTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && moderate.isChecked() && loseless.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.55);
                    newTDEE = mTDEE - (mTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && moderate.isChecked() && maintain.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.55);
                    newTDEE = mTDEE;
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (mTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && moderate.isChecked() && gainmore.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.55);
                    newTDEE = mTDEE + (mTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && moderate.isChecked() && gainless.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.55);
                    newTDEE = mTDEE + (mTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && extreme.isChecked() && losemore.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.725);
                    newTDEE = mTDEE - (mTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && extreme.isChecked() && loseless.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.725);
                    newTDEE = mTDEE - (mTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && extreme.isChecked() && maintain.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.725);
                    newTDEE = mTDEE;
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (mTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && extreme.isChecked() && gainmore.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.725);
                    newTDEE = mTDEE + (mTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (male.isChecked() && extreme.isChecked() && gainless.isChecked()) {
                    mREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))+5);
                    mTDEE = (mREE*1.725);
                    newTDEE = mTDEE + (mTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                }

                if (female.isChecked() && sedentary.isChecked() && losemore.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.2);
                    newTDEE = fTDEE - (fTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && sedentary.isChecked() && loseless.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.2);
                    newTDEE = fTDEE - (fTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && sedentary.isChecked() && maintain.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.2);
                    newTDEE = fTDEE;
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && sedentary.isChecked() && gainmore.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.2);
                    newTDEE = fTDEE + (fTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && sedentary.isChecked() && gainless.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.2);
                    newTDEE = fTDEE + (fTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && light.isChecked() && losemore.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.375);
                    newTDEE = fTDEE - (fTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && light.isChecked() && loseless.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.375);
                    newTDEE = fTDEE - (fTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && light.isChecked() && maintain.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.375);
                    newTDEE = fTDEE;
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && light.isChecked() && gainmore.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.375);
                    newTDEE = fTDEE + (fTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && light.isChecked() && gainless.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.375);
                    newTDEE = fTDEE + (fTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && moderate.isChecked() && losemore.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.55);
                    newTDEE = fTDEE - (fTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && moderate.isChecked() && loseless.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.55);
                    newTDEE = fTDEE - (fTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && moderate.isChecked() && maintain.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.55);
                    newTDEE = fTDEE;
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && moderate.isChecked() && gainmore.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.55);
                    newTDEE = fTDEE + (fTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && moderate.isChecked() && gainless.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.55);
                    newTDEE = fTDEE + (fTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && extreme.isChecked() && losemore.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.725);
                    newTDEE = fTDEE - (fTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && extreme.isChecked() && loseless.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.725);
                    newTDEE = fTDEE - (fTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && extreme.isChecked() && maintain.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.725);
                    newTDEE = fTDEE;
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && extreme.isChecked() && gainmore.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.725);
                    newTDEE = fTDEE + (fTDEE*.2);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                } else if (female.isChecked() && extreme.isChecked() && gainless.isChecked()) {
                    fREE = ((10*lb)+(6.25*(f+i))-(5*(Double.parseDouble(editAge.getText().toString())))-161);
                    fTDEE = (fREE*1.725);
                    newTDEE = fTDEE + (fTDEE*.1);
                    netProt = ((Double.parseDouble(editWeight.getText().toString()))*(0.825))*4;
                    netFat = (newTDEE*.25);
                    netCarb = (newTDEE - (netProt+netFat));
                    totProt = (netProt/4);
                    totFat = (netFat/9);
                    totCarb = (netCarb/4);
                    double a = Math.round(newTDEE*100.0)/100.0;
                    double b = Math.round(totProt*100.0)/100.0;
                    double c = Math.round(totFat*100.0)/100.0;
                    double d = Math.round(totCarb*100.0)/100.0;
                    bundle.putString("newTDEE", Double.toString(a));
                    bundle.putString("totProt", Double.toString(b));
                    bundle.putString("totFat", Double.toString(c));
                    bundle.putString("totCarb", Double.toString(d));
                }

                intent.putExtras(bundle);
                startActivity(intent);
            }
        });
    }
}
